[package]
name = "rs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
created-swarm = { git = "https://github.com/fluencelabs/rust-peer.git", branch = "master", package = "created-swarm" }
multiaddr = { version = "^0.14.0" }
